[package]
name = "cove"
version = "0.8.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/immodestproposal/cove"
description = """
Casts Of Varying Elegance (COVE): extension traits for casting numerical types
"""

[features]
default = ["std"]
std = []