[package]
name = "cove"
version = "0.2.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/immodestproposal/cove"
description = """
Casts Of Varying Elegance (COVE): extensions traits for casting numerical types
"""